spring:
  application:
    name: asset-spy-auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/asset-spy-db
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: asset_spy_user_service_db
        format_sql: true
