CREATE SCHEMA IF NOT EXISTS asset_spy_user_service_db;

CREATE TABLE IF NOT EXISTS asset_spy_user_service_db.users
(
    id            bigint PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    username      varchar(50) UNIQUE NOT NULL,
    description   text               NOT NULL,
    date_of_birth date               NOT NULL,
    created_at    timestamptz        NOT NULL,
    external_id   uuid               NOT NULL UNIQUE
);